# Generated by Django 4.0 on 2021-12-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspace',
            options={'verbose_name': 'Parking Space', 'verbose_name_plural': 'Parking Spaces'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
