# Generated by Django 4.0 on 2021-12-10 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_parkingspace_options_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 1, 42, 17, 426442)),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 21, 42, 17, 426442)),
        ),
    ]
