# Generated by Django 4.0 on 2021-12-10 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_date_remove_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 1, 43, 19, 482359)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 21, 43, 19, 482359)),
        ),
    ]
