# Generated by Django 4.0 on 2021-12-15 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_date_end_alter_booking_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 17, 52, 32, 570559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 13, 52, 32, 570559, tzinfo=utc)),
        ),
    ]
