export const GET_BOOKING_LIST = 'GET_BOOKING_LIST';
export const CHANGE_BOOKING = 'CHANGE_BOOKING';
export const ADD_BOOKING = 'ADD_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const GET_PARKING_SPACES = 'GET_PARKING_SPACES'